---
title: "Notes about DataCamp"
output: html_notebook
---

Not much effort to provide conceptual image around git add/diff/commit.  No running analogies.

Jumps around a bit from exercise to exercise (ie editing different files (data vs report).  Some placing of the students in context might be good?  Ability to scroll back up would be interesting.

You should always be able to use `git status`/`ls` without being told it is a "Wrong submission"

Seems that tab doesn't work to complete branch names?

https://campus.datacamp.com/courses/introduction-to-git-for-data-science/working-with-branches?ex=6

Says "You are in master branch" but actually seem to start in `deleting-report` branch.

The correct command gives an error.

$ git merge summary-statistics master
error: merge is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm<file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

https://campus.datacamp.com/courses/introduction-to-git-for-data-science/working-with-branches?ex=7

Doesn't seem to be well motivated.  I suggest having a branch as a detail for one of the steps.  Show a simple insertion, which shouldn't cause a conflict, and then a change which should.

https://campus.datacamp.com/courses/introduction-to-git-for-data-science/working-with-branches?ex=8

Not sure if it matters but the instructions don't tell you the desired final state for the paper.

-------------------

