---
title: "WikiProject Databases"
author: Gaurav Lalwani
output: html_document
---

# Contribution

I made many contributions to the Wikiproject: Databases and each contribution in its way is an own unique experience and learning curve. First I tried to edit the Wiki pages (SQL, Blockchain e.t.c) with some relevant content. Much to my surprise, there was no initial assessment required and I could directly publish those changes to the main site. Next I tried to contribute in the talk page by helping a fellow Wikipedian with its query. But I suppose the user was not active to respond to my note. The talk pages were always polite and helped each user upgrade their skills by making them learn something new about their query.  I was surprised to see the level of contributions to the page in the past month even though Wikiproject: Databases is a semi-Active project. One of the other aspects to which I contributed was the open tasks. I found out that these tasks were raised by other users and many of these tasks were also part of the talk pages. I contributed to some of the tasks (eg citations) and found out that I can edit these tasks and they will be reviewed by other users. Fellow wikipedians can also undo your work or thank you for your contribution.

# Assessment

I tried to find the top pages which were active and made contributions to those pages so that my work could be assessed by other users. Wikipedia has a table of popular pages according to the number of views per day that indicate the level of activeness. I found it interesting to see new topics like 'Blockchain' at the top of the list. Even though my contributions to the popular pages were too low to be reviewed, I could see constant changes in the top pages (peer review of contributed work) and the talk pages filled with new suggestions to upgrade the existing material. Wikipedia also has symbol on pages to indicate the featured content which indicated excellence in the assessment of Wikipedians. Even though my project had many common topics like SQL I rarely found these symbols due to the constant changes imparted onto the page. One of the improvements could be to include the process of authorization from a fellow Wikipedian before publishing content on the main page (like accepting the pull request from the contributor).

# Community Portal

One of the most important features of a Wikiproject is the Community portal which made me feel that I am part of a big project. This portal combines all Wiki projects together thus giving a huge database of all the open end issues and talks in different projects. I also worked on other non-technical projects within the portal and solve trivial issues like including images and proof reading.

# Conclusion

My first experience with Wikipedia which let me publish my changes directly to the site made me wonder the authenticity of all the Wikipedia pages but seeing the work done by other users, assessment and the focus of the community to include some evidence before stating facts made me change my perspective towards the community. The assessment done by fellow users and  the changes incorporated every day to the entire community as a whole makes Wikipedia one of the biggest open source projects which connects people all across the globe.

# References

En.wikipedia.org. Wikipedia:WikiProject Databases. <https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Databases> 