---
title: "Scanlation Group Experience Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Taka Kodani\
4/29/18

Having chosen scanlation groups as the peer production community to participate in, I first undertook a search process by identifying promising groups to join. In the end, I decided on a scanlation group called LOLScans as the first one I would attempt to reach out to. Several days after I submitted an email to them stating who I was and what I intended to do, I received a response saying that they were willing to acommodate my request. They asked me to do a short Japanese translation test (which involved translating two pages of manga from Japanese to English) and to join the group's Discord server.

After completing both, I was contacted by one of the admins of the group, KapteynG, through direct messaging on Discord while we were both online. Having passed the test, I was given an explanation on what the scanlation process entailed. She then sent me a Google Drive link to a zipped folder, which contained the raws for a chapter I was assigned the translation for. During the conversation I asked her if there was a deadline I should meet and was met with a long pause, followed by this message:

> Because you're a translator, it really depends on your schedule. We can't move on without your script anyway.

I think, having never been given a task or assignment and not gotten a due date for it within school and work environments, this response came as a bit of a surprise to me, but it made sense for a community such as this. The members are all volunteers who do what they do because it's fun. The group has a casual atmosphere, and making people do what they don't want to do is contrary its philosophy--otherwise, members would likely stop contributing and leave the group.

I spent two weeks translating the raws that were sent to me--Chapter 91 of a manga called Nobunaga's Chef--which was difficult to do because the story takes place in feudal Japan and dialogue is in archaic Japanese. With the assistance of Google Translate and online Japanese dictionaries, I wrote the translated script in a text file and sent it to KapteynG directly through Discord.

One important thing to note is that a typical scanlation group always wants to recruit contributors who will stay committed on a long-term basis. Because I had stated upfront I only intended to contribute a few chapters, it became clear that I was not going to get the kind of access staff members get when they join. In the end, I was able to accomplish what I had set out to do, but I was not privy to the internal staff discussions, was not admitted to the staff-only channels on the Discord server, and did not have access to the files that were in progress. I am certain they will use my translation, but I will not be able to witness it be reviewed. Although this was somewhat expected, what I did not expect was how this would detract from experiencing a tangible sense of accomplishment. To say the least, working on this single task has sprouted newfound appreciation for the volunteers who do this week in, week out, just so readers like me could blow through a single chapter in 5-10 minutes.


