---
title: "Participation Paper"
author: "Yan Zhan"
date: "11/30/2019"
output: pdf_document
link-citations: yes
linkcolor: blue
bibliography: pp_references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Citations use APA format

## Introduction
I participated in projects in a peer production community named *Baidu Baike*. "It is a Chinese-language, collaborative, web-based encyclopedia owned and produced by the Chinese search engine Baidu. Its test version was released on 20 April 2006, and within three weeks the encyclopedia had grown to more than 90,000 articles."[@noauthor_baidu_nodate]

"Baidu officially states that *Baidu Baike* serves as an online encyclopedia as well as information storage space for netizens. *Baidu Baike* claims "equality", "cooperation", "sharing" and "freedom" spiritually, and connect this online platform with search engines technically in order to fulfil the needs of the users for information of different levels."[@noauthor_baidu_2019]


## Project 1
#### Motivation
I searched “The University of Texas School of Information” in *Baidu Baike* and found nothing in it. Thus, I decided to create an entry of "The University of Texas School of Information" in order to introduce our school to people who might be interested in. 

#### Process
1. I searched other educational institutions’ entries in *Baidu Baike* and figured out what kinds information needed  and what the catalogue would look like in the end.

2. I collected its history, academic programs, current faculty and notable alumni from Information School’s official website and the rankings from US News’s website.

3. I registered an account in Baidu.

4. I began to create the entry in *Baidu Baike* and listed references.

5. I previewed final result, checked and submitted it.

6. I received a message that my entry failed to pass system audit because of including promotions and advertisements.

7. I read and checked my version over and over again and found no words indicating advertising.

8. I started an appeal.

9. I am still waiting for message now.

## Project 2
#### Motivation
I found that the entry of The University of Texas at Austin in *Baidu Baike* had some outdated information, so I wanted to update them and share them with public.

#### Process
1. I read the original version and compared it with the latest information. 

2. I found that some ranking information are of 2018 or even earlier. Also, there are more academic programs in UT than listed in the website.

3. I collected all these latest information and edited the entry.

4. I submitted and waited for message.

5. I got a message saying that I deleted one useful information.

6. I started checking the entry and found that I deleted one reference of the original version accidentally.

7. I corrected and submitted it again.

## Comparison with Expectation
1. The editing process is easier than I thought. Before that, I thought there may be lots of restrictions of editing or creating entries. In fact, after registering a Baidu account, I could directly create an entry or edit any entry which was already there. 

2. The review process is much more complicated than my expectation. I thought that someone would review the entry I submitted, check whether the information provided was correct and then decide whether to pass it or not. However, actually the updated version would be checked by system first and then by persons. If failed, I could ask for a manual review and provide reasons and evidences why I disagree with the decision

3. The whole process is longer than I expected, because I asked for a manual review around a week ago. However, I still don’t receive any message.

## Conclusion
To put it in a nutshell, *Baidu Baike* is a typical peer production community. On the one hand, it has all characteristics of a peer production community since it is free enough that anyone can create and edit its entries, the whole process is open and the results will be shared with public. On the  other hand, *Baidu Baike* has strict review mechanism, which will, without doubt, make it a quality community.

# References

