---
title: "Peer Production Experience Report"
author: Tina Lassiter
date: December 1, 2019
output: html_document
bibliography: PPlibrary.bib
---

Citation style: The Chicago Manual of Style (17th edition)

# BookCrossing experience

## I. Expectations
I picked [BookCrossing](http://BookCrossing.com) with the hope to track books traveling from reader to reader, and to be part of a community that shares books, thus a "community of interest"[@TypesCommunityActivity2012].

BookCrossing has been characterized as an example of "anonymous sharing"  and "collective reciprocity" [@corciolaniGiftgivingSharingCommodity2014]. There is no direct exchange. I mostly do not know who will read my books, and I also do not know whose books I catch. The motivation is an intrinsic one, the reward is the activity itself [see @ryanIntrinsicExtrinsicMotivations2000], for me the release of books.

## II. My participation at BookCrossing
Over two months, I registered 23 books with BookCrossing, mostly fiction, and caught one book.

To register, I wrote online-notes, printed out labels, created unique identifiers through BookCrossing.com and labeled the books. Most of them I released into free libraries in Austin, 8  into “*The BookShelf*”, a BookCrossing Zone. I gave one book to a friend, and sent one book to a BookCrosser in Colorado who wanted  it. After releasing, I made another entry in each journal online.

So far, I have not heard from any of the general free library releases. One library was completely emptied. Another one had some of my books taken but not all. For one book in “*The Bookshelf*”, I received a friendly note from another BookCrosser online, but it was put right back. I motivated a friend to participate. She read the book I gave her, wrote a review and then released it in her own library which she turned into a BookCrossing Zone. For the book I sent away, I received a thank-you-note in the journal but no review.

I found books online that were supposed to be on “*The BookShelf*” but could not find them. I picked up another BookCrossing-book there instead and made a found entry online. I checked the free libraries for other BookCrossing books, but did not find any.


## III. My observations and feelings
The online instructions for BookCrossing were easy to follow, and I was free in creating my entries. Nobody corrected or reviewed them. The note from the other BookCrosser was a warm welcome from the community. Technical support was quick and helpful. This was all pleasant.

It was frustrating that books were purged from little libraries. I was disappointed to not receive much tracking information. I had envisioned creating travel logs and reading reviews. I also hoped to find BookCrossing-books more easily. 

Controlled releases were more satisfying, especially the one to my friend, though I could just have lent her the book. Sending the book was a lot of effort for little reward. I had to inquire about the address, pack it and ship it at my own cost. The thank-you-note online was nice but not motivating enough to repeat it.
   
Overall, the hope to track books was disappointed, but I felt being part of a community of book lovers with a common goal of sharing the love of reading, even if you don’t know where your books travel to. 
 
# References



