---
title:
output:
  revealjs::revealjs_presentation:
    theme: moon
    smart: true
    background_transition: convex
---

## {data-background=collage.png}

<div><h1>PEER PRODUCTION PARTICIPATION EXPERIENCE</h1></div>
<div><h4>TAKA KODANI</h4></div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Scanlation

- Amateur process by which manga is **scanned** and **translated** from one language into another

- Performed by self-organized scanlation groups, of which there are close to 1,000 that have been active within the past six months

- Common roles include the scanner, translator, cleaner, typesetter, proofreader, and editor

## LOLScans {data-background=lolscans.png}

- Started in October 2012
- Consists of 40+ active staff members
- Releases 2-3 chapters per week
- Currently working on 20 manga series

## A Chef of Nobunaga - Chapter 91 {data-background=NNC.png}

## {data-background=script-1.png}

<div style="text-align:left;"><h2>Translation work</h2>

- Simple text file
- Everything translated
- Formatting
- Submitted via Discord

</div>

## Final Thoughts

- Peer production largely takes place internally
- Stating my intention to contribute only a few chapters of translation led to access limitations
- Communication was mostly conducted through a single point of contact
- While insightful, experience was consequently not as extensive as hoped
- Gained appreciation for the community, however, and learned how members devoted their time and efforts to work together to produce content for something they are passionate about