---
title: "Peer Production Participation"
author: "Nimish Kate"
date: "April 30, 2018"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---
output:
  ioslides_presentation: default
  html_document: default
---
# Wiki Transcripts

*A peer production activity.*

# Introduction

- Unavailibility of transcripts for Movies and TV shows
- Transcripts.wikia.com - a fan-based peer production community
- Topic - **The Harry Potter movie franchise**

# The Problem

> (A silver doe flies out through the window.)
>
> Dumbledore: After all this time?
>
> Snape: Always.
>

* The structure:
    + Parentheses depict the description.
    + Colon separates the character from its line.
  
* The issues:
    + Inconsistencies in the above structure
    + Inconsistencies in the character names
    + Incorrect content

# The Process

> Scene { Description, Dialogue { Character, Line } }

- A Python Parser reads the text and raises exceptions for every inconsistency
- A database of all characters replaces first names with last names

Steps:

1. Resolving format inconsitencies
2. Resolving name inconsistencies
3. Resolving content inconsistencies

# The Analysis

The community:

- Summarize every change
- declare a minor change
- Prompt emails to notify removal of irrelevant changes
- Ignore minor changes

# The Reflections

- The community actively rectifies errors.
- The notification is prompt.
- The community places a certain degree of trust
- Manual editing is a pain

*I uploaded the parser algorithm to the discussion forum.*
