---
title: "Experience Report"
author: "Pedro Seguel"
date: "5/01/2018"
output: ioslides_presentation
---

## Project

- **Open Austin:** Civic Tech community
- **Initial idea:** *Crowdsource Texas school board election info*
- **Final idea:** *Request-yo-bike*

## Request-yo-bike

- **Community Action Night**: Hoping to meet project leaders.
- **Project&#39;s goal:** Simplify the process of requesting a free installation of bike corrals on the right of way/parking spot close to businesses to the city government.
- It focuses on reducing the efforts from the requester by 3 simple steps:
1. Select the location on the map
2. Review/Edit the information
3. Submit

## Participation

- **Setup of the ecosystem:** Leader&#39;s support and feedback.
- **The first contribution!** Reporting bugs in the project&#39;s documentation.
- **Finding new ways to contribute:** The issue that I spotted was solved during the week.

## Securing inclusive environments

- The use of gender pronouns: (she/her, they/them, he/him, ze/hir).
- Anti-Harassment Policy and resources for project leaders.
- Non-tech audiences: using inclusive language.  

