---
title: "Peer Production Experience Report: Caprine"
output: html_document
bibliography: bibliography.bib
csl: https://www.zotero.org/styles/modern-language-association?source=1
---

Florian Janke  
_Citations use MLA format_

I created a fork of the [Caprine GitHub repository](https://github.com/sindresorhus/caprine) and cloned this copy down to my machine. The repository had some information on how to start a local development copy of the project. I was then able to make changes to the code and restart the local build to test the changes. When pushing up the changes back to GitHub, a script ran on my machine that ran some tests to verify my changes. This was implemented using git hooks through [husky](https://github.com/typicode/husky). I often encountered style issues that I needed to fix before I could actually push up my code.

To determine what I wanted to work on, I went through the open issues on GitHub and looked at issues I thought were interesting and I would be able to work on. I spent some time looking through the code to try to find where I should implement the changes. One of the issues I ended up working on seemed abandoned. This was because, after the issue was created, the developers decided that code in another repository would need to be changed before code could be changed in Caprine. This is a development interdependency [@lindberg_coordinating_2016] as one task needs to be completed before another can be.

At first I made my changes directly on my master branch, but later on I wanted to open multiple PRs to address different issues. To create multiple PRs with different code changes, I created feature branches. The description of the PRs always referred to the issue that was being addressed and included supplementary information as needed. Such information included screenshots of visual changes, rationale behind why code was implemented a certain way, and questions in case something was potentially ambiguous.

Once the PR was created, Travis CI automatically ran tests again to verify the changes and make sure nothing broke. In addition to the automated tests, the owner of the repo, Sindre Sorhus, reviewed the changes. In two of the four PRs, changes were requested. In one of those, another maintainer, Jarek Radosz was pulled in for review. In that instance, the PR stalled while Radosz' review was pending and after a week I followed up asking if there was any update. The PR was merged in shortly after with just the prior approval. The entire process of use of continuous integration and evaluation of the PR is very similar to the description in the paper by @vasilescu_quality_2015. The process of gaining approval on a PR is a form of a developer interdependency [@lindberg_coordinating_2016].

The first PR I contributed was relatively minor, but I got a comment from the owner of the project thanking me for my contribution, which I appreciated. I also liked that I got some review on the other PRs as it made me more aware of the code and implementation choices in this project. Through these comments, contributing to the project made my feel the motivation of _understanding_ and _enhancement_ described in the context of Wikipedia by @nov_what_2007. The experience contributing to the Caprine project was a pleasant and successful one as my changes got merged in relatively painlessly. They did go according to the predictions described in the first paper.

# Works Cited
